(deftheme plain-white
  "Created 2015-03-09.")

(let* ((foreground "black")
       (background "white")
       (highlight "grey90")
       (region "light blue")
       )
  (custom-theme-set-faces
   'plain-white
   `(default ((t (:background ,background :foreground ,foreground))))
   `(cursor ((t (:foreground ,background :inverse-video t))))
   `(escape-glyph ((t (:foreground "#6c71c4" :underline nil :weight normal))))
   '(minibuffer-prompt ((t (:foreground "#000000" :underline nil :weight normal))))
   `(highlight ((t (:background ,highlight :underline nil :weight normal))))
   `(region ((t (:background ,region :foreground ,background :underline nil :weight normal))))
   '(shadow ((t (:foreground "#93a1a1" :underline nil :weight normal))))
   '(secondary-selection ((t (:background "#eee8d5" :underline nil :weight normal))))
   '(trailing-whitespace ((t (:background "#dc322f" :underline nil :weight normal))))
   '(font-lock-builtin-face ((t (:foreground "black" :underline nil :slant normal :weight normal))))
   '(font-lock-comment-delimiter-face ((t (:foreground "#93a1a1" :underline nil :slant normal :weight normal))))
   '(font-lock-comment-face ((t (:foreground "#93a1a1" :underline nil :weight normal))))
   '(font-lock-constant-face ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-doc-face ((t (:foreground "black" :underline nil :slant normal :weight normal))))
   '(font-lock-function-name-face ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-keyword-face ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-negation-char-face ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-preprocessor-face ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-regexp-grouping-backslash ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-regexp-grouping-construct ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-string-face ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-type-face ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-variable-name-face ((t (:foreground "black" :underline nil :weight normal))))
   '(font-lock-warning-face ((t (:foreground "black" :underline nil :weight normal))))
   '(button ((t (:underline nil :weight normal))))
   '(link ((t (:foreground "#b58900" :underline nil :weight normal))))
   '(link-visited ((t (:foreground "#b58900" :underline nil :weight normal))))
   `(fringe ((t (:background ,background :foreground "#93a1a1" :underline nil :weight normal))))
   `(header-line ((t (:background ,background :foreground "#000000" :box (:line-width 2 :color ,background :style unspecified) :overline nil :underline nil :weight normal))))
   '(tooltip ((t (:inherit (variable-pitch) :background "#DEB542" :foreground "#7B6000" :underline nil :weight normal))))
   '(mode-line ((t (:background "#3c3c3c" :foreground "#ffffff" :box (:line-width 1 :color "#eee8d5" :style unspecified) :overline "#eee8d5" :underline nil :weight normal))))
   '(mode-line-buffer-id ((t (:foreground "#ffffff" :underline nil :weight normal))))
   '(mode-line-emphasis ((t (:underline nil :weight normal))))
   '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button) :underline nil :weight normal))))
   `(mode-line-inactive ((t (:background "#999999" :foreground "#93a1a1" :box (:line-width 1 :color ,background :style unspecified) :overline "#eee8d5" :underline nil :weight normal))))
   `(isearch ((t (:background "#d33682" :foreground ,background :underline nil :weight normal))))
   `(isearch-fail ((t (:background ,background :foreground "#dc322f" :underline nil :weight normal))))
   `(lazy-highlight ((t (:background "#b58900" :foreground ,background :underline nil :weight normal))))
   '(match ((t (:background "#eee8d5" :foreground "#586e75" :underline nil :weight normal))))
   '(next-error ((t (:inherit (region) :underline nil :weight normal))))
   '(query-replace ((t (:inherit (isearch) :underline nil :weight normal))))))

(provide-theme 'plain-white)
